// src/lib/api/items.ts
// Albion Online item IDs for market analysis
// Format: T{tier}_{category}_{name}@{enchantment}

export const ITEM_CATEGORIES = {
  ARMOR: "armor",
  WEAPON: "weapon",
  GATHERING: "gathering",
  CRAFTING: "crafting",
  RESOURCE: "resource",
};

// Core tradeable items for flip analysis
export const TRADEABLE_ITEMS: string[] = [
  // Swords T4-T8 all enchantments
  "T4_MAIN_SWORD",
  "T4_MAIN_SWORD@1",
  "T4_MAIN_SWORD@2",
  "T4_MAIN_SWORD@3",
  "T5_MAIN_SWORD",
  "T5_MAIN_SWORD@1",
  "T5_MAIN_SWORD@2",
  "T5_MAIN_SWORD@3",
  "T6_MAIN_SWORD",
  "T6_MAIN_SWORD@1",
  "T6_MAIN_SWORD@2",
  "T6_MAIN_SWORD@3",
  "T7_MAIN_SWORD",
  "T7_MAIN_SWORD@1",
  "T7_MAIN_SWORD@2",
  "T7_MAIN_SWORD@3",
  "T8_MAIN_SWORD",
  "T8_MAIN_SWORD@1",
  "T8_MAIN_SWORD@2",
  "T8_MAIN_SWORD@3",
  // Crossbows
  "T4_2H_CROSSBOW",
  "T4_2H_CROSSBOW@1",
  "T4_2H_CROSSBOW@2",
  "T4_2H_CROSSBOW@3",
  "T5_2H_CROSSBOW",
  "T5_2H_CROSSBOW@1",
  "T5_2H_CROSSBOW@2",
  "T5_2H_CROSSBOW@3",
  "T6_2H_CROSSBOW",
  "T6_2H_CROSSBOW@1",
  "T6_2H_CROSSBOW@2",
  "T6_2H_CROSSBOW@3",
  "T7_2H_CROSSBOW",
  "T7_2H_CROSSBOW@1",
  "T7_2H_CROSSBOW@2",
  "T7_2H_CROSSBOW@3",
  "T8_2H_CROSSBOW",
  "T8_2H_CROSSBOW@1",
  "T8_2H_CROSSBOW@2",
  "T8_2H_CROSSBOW@3",
  // Bows
  "T4_2H_BOW",
  "T4_2H_BOW@1",
  "T4_2H_BOW@2",
  "T4_2H_BOW@3",
  "T5_2H_BOW",
  "T5_2H_BOW@1",
  "T5_2H_BOW@2",
  "T5_2H_BOW@3",
  "T6_2H_BOW",
  "T6_2H_BOW@1",
  "T6_2H_BOW@2",
  "T6_2H_BOW@3",
  "T7_2H_BOW",
  "T7_2H_BOW@1",
  "T7_2H_BOW@2",
  "T7_2H_BOW@3",
  "T8_2H_BOW",
  "T8_2H_BOW@1",
  "T8_2H_BOW@2",
  "T8_2H_BOW@3",
  // Plate armor
  "T4_ARMOR_PLATE_SET1",
  "T4_ARMOR_PLATE_SET1@1",
  "T4_ARMOR_PLATE_SET1@2",
  "T4_ARMOR_PLATE_SET1@3",
  "T5_ARMOR_PLATE_SET1",
  "T5_ARMOR_PLATE_SET1@1",
  "T5_ARMOR_PLATE_SET1@2",
  "T5_ARMOR_PLATE_SET1@3",
  "T6_ARMOR_PLATE_SET1",
  "T6_ARMOR_PLATE_SET1@1",
  "T6_ARMOR_PLATE_SET1@2",
  "T6_ARMOR_PLATE_SET1@3",
  "T7_ARMOR_PLATE_SET1",
  "T7_ARMOR_PLATE_SET1@1",
  "T7_ARMOR_PLATE_SET1@2",
  "T7_ARMOR_PLATE_SET1@3",
  "T8_ARMOR_PLATE_SET1",
  "T8_ARMOR_PLATE_SET1@1",
  "T8_ARMOR_PLATE_SET1@2",
  "T8_ARMOR_PLATE_SET1@3",
  // Leather armor
  "T4_ARMOR_LEATHER_SET1",
  "T4_ARMOR_LEATHER_SET1@1",
  "T4_ARMOR_LEATHER_SET1@2",
  "T4_ARMOR_LEATHER_SET1@3",
  "T5_ARMOR_LEATHER_SET1",
  "T5_ARMOR_LEATHER_SET1@1",
  "T5_ARMOR_LEATHER_SET1@2",
  "T5_ARMOR_LEATHER_SET1@3",
  "T6_ARMOR_LEATHER_SET1",
  "T6_ARMOR_LEATHER_SET1@1",
  "T6_ARMOR_LEATHER_SET1@2",
  "T6_ARMOR_LEATHER_SET1@3",
  "T7_ARMOR_LEATHER_SET1",
  "T7_ARMOR_LEATHER_SET1@1",
  "T7_ARMOR_LEATHER_SET1@2",
  "T7_ARMOR_LEATHER_SET1@3",
  "T8_ARMOR_LEATHER_SET1",
  "T8_ARMOR_LEATHER_SET1@1",
  "T8_ARMOR_LEATHER_SET1@2",
  "T8_ARMOR_LEATHER_SET1@3",
  // Cloth armor
  "T4_ARMOR_CLOTH_SET1",
  "T4_ARMOR_CLOTH_SET1@1",
  "T4_ARMOR_CLOTH_SET1@2",
  "T4_ARMOR_CLOTH_SET1@3",
  "T5_ARMOR_CLOTH_SET1",
  "T5_ARMOR_CLOTH_SET1@1",
  "T5_ARMOR_CLOTH_SET1@2",
  "T5_ARMOR_CLOTH_SET1@3",
  "T6_ARMOR_CLOTH_SET1",
  "T6_ARMOR_CLOTH_SET1@1",
  "T6_ARMOR_CLOTH_SET1@2",
  "T6_ARMOR_CLOTH_SET1@3",
  "T7_ARMOR_CLOTH_SET1",
  "T7_ARMOR_CLOTH_SET1@1",
  "T7_ARMOR_CLOTH_SET1@2",
  "T7_ARMOR_CLOTH_SET1@3",
  "T8_ARMOR_CLOTH_SET1",
  "T8_ARMOR_CLOTH_SET1@1",
  "T8_ARMOR_CLOTH_SET1@2",
  "T8_ARMOR_CLOTH_SET1@3",
  // Helmets
  "T4_HEAD_PLATE_SET1",
  "T4_HEAD_PLATE_SET1@1",
  "T4_HEAD_PLATE_SET1@2",
  "T4_HEAD_PLATE_SET1@3",
  "T5_HEAD_PLATE_SET1",
  "T5_HEAD_PLATE_SET1@1",
  "T5_HEAD_PLATE_SET1@2",
  "T5_HEAD_PLATE_SET1@3",
  "T6_HEAD_PLATE_SET1",
  "T6_HEAD_PLATE_SET1@1",
  "T6_HEAD_PLATE_SET1@2",
  "T6_HEAD_PLATE_SET1@3",
  "T7_HEAD_PLATE_SET1",
  "T7_HEAD_PLATE_SET1@1",
  "T7_HEAD_PLATE_SET1@2",
  "T7_HEAD_PLATE_SET1@3",
  "T8_HEAD_PLATE_SET1",
  "T8_HEAD_PLATE_SET1@1",
  "T8_HEAD_PLATE_SET1@2",
  "T8_HEAD_PLATE_SET1@3",
  // Boots
  "T4_SHOES_PLATE_SET1",
  "T4_SHOES_PLATE_SET1@1",
  "T4_SHOES_PLATE_SET1@2",
  "T4_SHOES_PLATE_SET1@3",
  "T5_SHOES_PLATE_SET1",
  "T5_SHOES_PLATE_SET1@1",
  "T5_SHOES_PLATE_SET1@2",
  "T5_SHOES_PLATE_SET1@3",
  "T6_SHOES_PLATE_SET1",
  "T6_SHOES_PLATE_SET1@1",
  "T6_SHOES_PLATE_SET1@2",
  "T6_SHOES_PLATE_SET1@3",
  "T7_SHOES_PLATE_SET1",
  "T7_SHOES_PLATE_SET1@1",
  "T7_SHOES_PLATE_SET1@2",
  "T7_SHOES_PLATE_SET1@3",
  "T8_SHOES_PLATE_SET1",
  "T8_SHOES_PLATE_SET1@1",
  "T8_SHOES_PLATE_SET1@2",
  "T8_SHOES_PLATE_SET1@3",
  // Staff weapons
  "T4_MAIN_ARCANESTAFF",
  "T4_MAIN_ARCANESTAFF@1",
  "T4_MAIN_ARCANESTAFF@2",
  "T4_MAIN_ARCANESTAFF@3",
  "T5_MAIN_ARCANESTAFF",
  "T5_MAIN_ARCANESTAFF@1",
  "T5_MAIN_ARCANESTAFF@2",
  "T5_MAIN_ARCANESTAFF@3",
  "T6_MAIN_ARCANESTAFF",
  "T6_MAIN_ARCANESTAFF@1",
  "T6_MAIN_ARCANESTAFF@2",
  "T6_MAIN_ARCANESTAFF@3",
  "T7_MAIN_ARCANESTAFF",
  "T7_MAIN_ARCANESTAFF@1",
  "T7_MAIN_ARCANESTAFF@2",
  "T7_MAIN_ARCANESTAFF@3",
  "T8_MAIN_ARCANESTAFF",
  "T8_MAIN_ARCANESTAFF@1",
  "T8_MAIN_ARCANESTAFF@2",
  "T8_MAIN_ARCANESTAFF@3",
  // Fire staff
  "T4_MAIN_FIRESTAFF",
  "T4_MAIN_FIRESTAFF@1",
  "T4_MAIN_FIRESTAFF@2",
  "T4_MAIN_FIRESTAFF@3",
  "T5_MAIN_FIRESTAFF",
  "T5_MAIN_FIRESTAFF@1",
  "T5_MAIN_FIRESTAFF@2",
  "T5_MAIN_FIRESTAFF@3",
  "T6_MAIN_FIRESTAFF",
  "T6_MAIN_FIRESTAFF@1",
  "T6_MAIN_FIRESTAFF@2",
  "T6_MAIN_FIRESTAFF@3",
  "T7_MAIN_FIRESTAFF",
  "T7_MAIN_FIRESTAFF@1",
  "T7_MAIN_FIRESTAFF@2",
  "T7_MAIN_FIRESTAFF@3",
  "T8_MAIN_FIRESTAFF",
  "T8_MAIN_FIRESTAFF@1",
  "T8_MAIN_FIRESTAFF@2",
  "T8_MAIN_FIRESTAFF@3",
  // Axes
  "T4_MAIN_AXE",
  "T4_MAIN_AXE@1",
  "T4_MAIN_AXE@2",
  "T4_MAIN_AXE@3",
  "T5_MAIN_AXE",
  "T5_MAIN_AXE@1",
  "T5_MAIN_AXE@2",
  "T5_MAIN_AXE@3",
  "T6_MAIN_AXE",
  "T6_MAIN_AXE@1",
  "T6_MAIN_AXE@2",
  "T6_MAIN_AXE@3",
  "T7_MAIN_AXE",
  "T7_MAIN_AXE@1",
  "T7_MAIN_AXE@2",
  "T7_MAIN_AXE@3",
  "T8_MAIN_AXE",
  "T8_MAIN_AXE@1",
  "T8_MAIN_AXE@2",
  "T8_MAIN_AXE@3",
  // Maces
  "T4_MAIN_MACE",
  "T4_MAIN_MACE@1",
  "T4_MAIN_MACE@2",
  "T4_MAIN_MACE@3",
  "T5_MAIN_MACE",
  "T5_MAIN_MACE@1",
  "T5_MAIN_MACE@2",
  "T5_MAIN_MACE@3",
  "T6_MAIN_MACE",
  "T6_MAIN_MACE@1",
  "T6_MAIN_MACE@2",
  "T6_MAIN_MACE@3",
  "T7_MAIN_MACE",
  "T7_MAIN_MACE@1",
  "T7_MAIN_MACE@2",
  "T7_MAIN_MACE@3",
  "T8_MAIN_MACE",
  "T8_MAIN_MACE@1",
  "T8_MAIN_MACE@2",
  "T8_MAIN_MACE@3",
  // Holy Staff
  "T4_MAIN_HOLYSTAFF",
  "T4_MAIN_HOLYSTAFF@1",
  "T4_MAIN_HOLYSTAFF@2",
  "T4_MAIN_HOLYSTAFF@3",
  "T5_MAIN_HOLYSTAFF",
  "T5_MAIN_HOLYSTAFF@1",
  "T5_MAIN_HOLYSTAFF@2",
  "T5_MAIN_HOLYSTAFF@3",
  "T6_MAIN_HOLYSTAFF",
  "T6_MAIN_HOLYSTAFF@1",
  "T6_MAIN_HOLYSTAFF@2",
  "T6_MAIN_HOLYSTAFF@3",
  "T7_MAIN_HOLYSTAFF",
  "T7_MAIN_HOLYSTAFF@1",
  "T7_MAIN_HOLYSTAFF@2",
  "T7_MAIN_HOLYSTAFF@3",
  "T8_MAIN_HOLYSTAFF",
  "T8_MAIN_HOLYSTAFF@1",
  "T8_MAIN_HOLYSTAFF@2",
  "T8_MAIN_HOLYSTAFF@3",
  // Bags
  "T4_BAG",
  "T4_BAG@1",
  "T4_BAG@2",
  "T4_BAG@3",
  "T5_BAG",
  "T5_BAG@1",
  "T5_BAG@2",
  "T5_BAG@3",
  "T6_BAG",
  "T6_BAG@1",
  "T6_BAG@2",
  "T6_BAG@3",
  "T7_BAG",
  "T7_BAG@1",
  "T7_BAG@2",
  "T7_BAG@3",
  "T8_BAG",
  "T8_BAG@1",
  "T8_BAG@2",
  "T8_BAG@3",
  // Cape
  "T4_CAPE",
  "T4_CAPE@1",
  "T4_CAPE@2",
  "T4_CAPE@3",
  "T5_CAPE",
  "T5_CAPE@1",
  "T5_CAPE@2",
  "T5_CAPE@3",
  "T6_CAPE",
  "T6_CAPE@1",
  "T6_CAPE@2",
  "T6_CAPE@3",
  "T7_CAPE",
  "T7_CAPE@1",
  "T7_CAPE@2",
  "T7_CAPE@3",
  "T8_CAPE",
  "T8_CAPE@1",
  "T8_CAPE@2",
  "T8_CAPE@3",
];

export function parseItemId(itemId: string): {
  tier: number;
  enchantment: number;
  baseName: string;
} {
  const enchantMatch = itemId.match(/@(\d)$/);
  const enchantment = enchantMatch ? parseInt(enchantMatch[1]) : 0;
  const baseId = enchantMatch ? itemId.slice(0, -2) : itemId;

  const tierMatch = baseId.match(/^T(\d)_/);
  const tier = tierMatch ? parseInt(tierMatch[1]) : 0;

  const baseName = baseId
    .replace(/^T\d_/, "")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (l) => l.toUpperCase())
    .replace(/Set\d$/i, "")
    .trim();

  return { tier, enchantment, baseName };
}

export function getItemImageUrl(itemId: string, quality: number = 1): string {
  const baseId = itemId.split("@")[0];
  const enchant = itemId.includes("@") ? itemId.split("@")[1] : "0";
  return `https://render.albiononline.com/v1/item/${baseId}.png?count=1&quality=${quality}&enchantment=${enchant}`;
}

export function formatItemName(itemId: string): string {
  const { tier, enchantment, baseName } = parseItemId(itemId);
  const enchStr = enchantment > 0 ? `.${enchantment}` : "";
  return `T${tier}${enchStr} ${baseName}`;
}
